create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_name text not null,
  customer_email text not null,
  total_amount integer not null check (total_amount > 0),
  status text not null default 'pending' check (status in ('pending','paid','processing','completed','expired','cancelled')),
  created_at timestamptz not null default now()
);
create table if not exists order_items (
  id uuid primary key default gen_random_uuid(), order_id uuid not null references orders(id) on delete cascade,
  product_id text not null, product_name text not null, price integer not null, quantity integer not null default 1
);
create table if not exists payments (
  id uuid primary key default gen_random_uuid(), order_id uuid not null unique references orders(id) on delete cascade,
  provider text not null default 'tokopay', reference_id text not null unique, provider_transaction_id text,
  payment_method text not null default 'qris', amount integer not null, status text not null default 'pending',
  qr_string text, qr_image_url text, raw_response jsonb, paid_at timestamptz, created_at timestamptz not null default now()
);

create table if not exists inventory (
  product_id text primary key,
  stock integer not null default 0 check (stock >= 0),
  price integer not null check (price > 0),
  active boolean not null default true,
  image_url text,
  updated_at timestamptz not null default now()
);
create table if not exists products (
  id text primary key,
  name text not null,
  category text not null,
  duration text not null,
  price integer not null check (price > 0),
  original_price integer check (original_price is null or original_price > 0),
  description text not null,
  terms text not null default '',
  icon text not null default '✦',
  badge text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create table if not exists product_packages (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references products(id) on delete cascade,
  name text not null,
  duration text not null,
  price integer not null check (price > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists product_packages_product_idx on product_packages(product_id, active);
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into categories (name) values ('Produktivitas'), ('Kreativitas'), ('Streaming'), ('Musik') on conflict (name) do nothing;
alter table inventory add column if not exists image_url text;
alter table categories add column if not exists description text not null default '';
alter table products add column if not exists terms text not null default '';
alter table products add column if not exists original_price integer;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do update set public = true;

create table if not exists account_inventory (
  id uuid primary key default gen_random_uuid(),
  product_id text not null,
  package_id uuid references product_packages(id) on delete set null,
  login text not null,
  password text not null,
  status text not null default 'available' check (status in ('available', 'sold', 'disabled')),
  assigned_order_id uuid references orders(id) on delete set null,
  created_at timestamptz not null default now(),
  sold_at timestamptz
);
alter table account_inventory add column if not exists package_id uuid references product_packages(id) on delete set null;
create index if not exists account_inventory_product_status_idx on account_inventory(product_id, status);
create index if not exists account_inventory_package_status_idx on account_inventory(package_id, status);

create table if not exists blog_posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  category text not null default 'Umum',
  excerpt text not null default '',
  content text not null default '',
  cover_url text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table blog_posts add column if not exists category text not null default 'Umum';
create index if not exists blog_posts_status_published_idx on blog_posts(status, published_at desc);

-- === Top Up Game via Digiflazz ===
alter table product_packages add column if not exists digiflazz_sku text;
alter table product_packages add column if not exists requires_customer_no boolean not null default false;
alter table product_packages add column if not exists customer_no_label text not null default 'User ID';

alter table order_items add column if not exists digiflazz_sku text;
alter table order_items add column if not exists customer_no text;
alter table order_items add column if not exists digiflazz_ref_id text;
alter table order_items add column if not exists digiflazz_status text;
alter table order_items add column if not exists digiflazz_sn text;

create index if not exists order_items_order_idx on order_items(order_id);